sudo: required
services:
  - docker

notifications:
  slack: intersysconsulting:hs8Bgk1ky4iAKc1tuX9oDlSX

branches:
  only:
    - development
    - master

before_install:
  - docker build -t ingangsters/react-ecommerce -f Dockerfile.dev .

script:
  - docker run -e CI=true ingangsters/react-ecommerce npm test
  - echo REACT_APP_API_URL="$REACT_APP_API_URL" > .env

before_deploy:
  - echo THIS IS ABOUT TO DEPLOY
  - git add --force .env

after_deploy:
  - git rm -r --cached .env

deploy:
  provider: elasticbeanstalk
  on:
    branch: development
  access_key_id:
    secure: "$EBS_DEV_KEY_ID"
  secret_access_key:
    secure: "$EBS_DEV_SECRET_KEY"
  region: "us-east-2"
  app: "ingangsters-web-dev"
  env: "IngangstersWebDev-env"
  bucket_name: "$EBS_DEV_BUCKET_NAME"
  skip_cleanup: true
