sudo: required
services:
  - docker

notifications:
  slack: intersysconsulting:Ps1F9l0Wa26G9o1AxcbyFcCM

branches:
  only:
    - development

before_install:
  - docker build -t ingangsters/react-ecommerce -f Dockerfile.dev .

script:
  - docker run -e CI=true ingangsters/react-ecommerce npm test
