sudo: required
services:
  - docker

notifications:
  slack: intersysconsulting:hs8Bgk1ky4iAKc1tuX9oDlSX

before_install:
  - docker build -t ingangsters/react-ecommerce -f Dockerfile.dev .

script:
  - docker run -e CI=true ingangsters/react-ecommerce npm test
