export const UPDATE_PRODUCTS = "ADMIN_UPDATE_PRODUCTS";
export const FETCHING_PRODUCTS = "ADMIN_FETCHING_PRODUCTS";
export const FINISHED_FETCHING_PRODUCTS = "ADMIN_FINISHED_FETCHING_PRODUCTS";
export const UPADTE_PAGINATOR = "ADMIN_UPDATE_PAGINATOR";
export const ADMIN_GET_SEARCH_PRODUCTS = "ADMIN_GET_SEARCH_PRODUCTS";
export const ADMIN_PRODUCT_NO_FOUND = "ADMIN_PRODUCT_NO_FOUND";
