export const ADMIN_BEGIN_FETCH_ORDERS = "ADMIN_BEGIN_FETCH_ORDERS";
export const ADMIN_UPDATE_ORDER_LIST = "ADMIN_UPDATE_ORDER_LIST";
export const ADMIN_SET_STATUS_LIST = "ADMIN_SET_STATUS_LIST";
export const ADMIN_SET_ACTIVE_STATUS_FILTER = "ADMIN_SET_ACTIVE_STATUS_FILTER";
export const ADMIN_CLEAR_STATUS_FILTER = "ADMIN_CLEAR_STATUS_FILTER";
