export const UPDATE_ADMIN_USER = "ADMIN_UPDATE_USER";
export const FETCHING_ADMIN_USERS = "ADMIN_FETCHING_USERS";
export const FINISHED_FETCHING_ADMIN_USERS = "ADMIN_FINISHED_FETCHING_USERS";
export const GET_ADMIN_USER = "GET_ADMIN_USER";
export const ADMIN_USERS_ERROR = "ADMIN_USERS_ERROR";
export const UPADTE_PAGINATOR = "ADMIN_USERS_UPDATE_PAGINATOR";
export const ADMIN_GET_SEARCH_USERS = "ADMIN_GET_SEARCH_USERS";
export const ADMIN_USER_NO_FOUND = "ADMIN_USER_NO_FOUND";
