export const SHIPPING_FORM_VALID = "SHIPPING_FORM_VALID";
export const SHIPPING_FORM_INVALID = "SHIPPING_FORM_INVALID";
export const BILLING_FORM_VALID = "BILLING_FORM_VALID";
export const BILLING_FORM_INVALID = "BILLING_FORM_INVALID";
