export const ORDER_BY_ENABLE_PRICE_LTH = "ORDER_BY_ENABLE_PRICE_LTH";
export const ORDER_BY_ENABLE_PRICE_HTL = "ORDER_BY_ENABLE_PRICE_HTL";
export const ORDER_BY_ENABLE_NAME_AZ = "ORDER_BY_ENABLE_NAME_AZ";
export const ORDER_BY_ENABLE_NAME_ZA = "ORDER_BY_ENABLE_NAME_ZA";
export const ORDER_BY_ENABLE_STOCK_LTH = "ORDER_BY_ENABLE_STOCK_LTH";
export const ORDER_BY_ENABLE_STOCK_HTL = "ORDER_BY_ENABLE_STOCK_HTL";
export const ORDER_BY_CLEAR_ALL = "ORDER_BY_CLEAR_ALL";

export const FILTERS_SET_SHIPPABLE_TRUE = "FILTERS_SET_SHIPPABLE_TRUE";
export const FILTERS_SET_SHIPPABLE_FALSE = "FILTERS_SET_SHIPPABLE_FALSE";
export const FILTERS_SET_AVAILABLE_TRUE = "FILTERS_SET_AVAILABLE_TRUE";
export const FILTERS_SET_AVAILABLE_FALSE = "FILTERS_SET_AVAILABLE_FALSE";
export const FILTERS_SET_PRICE_RANGE = "FILTERS_SET_PRICE_RANGE";
export const FILTERS_CLEAR_FILTERS = "FILTERS_CLEAR_FILTERS";

export const SEARCH_PRODUCTS = "SEARCH_ADMIN_PRODUCTS";
