export const SET_MOUSE_OVER_ACCOUNT_BUTTON = "SET_MOUSE_OVER_ACCOUNT_BUTTON";
export const SET_MOUSE_OVER_CART_BUTTON = "SET_MOUSE_OVER_CART_BUTTON";
export const ACCOUNT_BUTTON_CLICKED = "ACCOUNT_BUTTON_CLICKED";
export const TOGGLE_MENU_RESPONSIVE = "TOGGLE_MENU_RESPONSIVE";
