export const GET_PRODUCTS = "GET_PRODUCTS";
export const PRODUCTS_ERROR = "PRODUCTS_ERROR";
export const GET_SEARCH_PRODUCTS = "GET_SEARCH_PRODUCTS";
export const PRODUCTS_NOT_FOUND = "PRODUCTS_NOT_FOUND";
export const GET_FILTERED_PRODUCTS = "GET_FILTERED_PRODUCTS";
